# Generated by Django 6.0 on 2026-01-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pricealert'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceresult',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
